/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBarLogo: typeof import('./components/layout/AppBarLogo/AppBarLogo.vue')['default']
    AppBarTitle: typeof import('./components/layout/AppBarTitle/AppBarTitle.vue')['default']
    DarkMode: typeof import('./components/layout/DarkMode/index.vue')['default']
    Footer: typeof import('./components/layout/Footer/Footer.vue')['default']
    GalleryMenu: typeof import('./components/layout/GalleryMenu/GalleryMenu.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MenuCard: typeof import('./components/layout/MenuCard/MenuCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarMenu: typeof import('./components/layout/SidebarMenu/SidebarMenu.vue')['default']
  }
}
