/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimatedBackground: typeof import('./components/AnimatedBackground/AnimatedBackground.vue')['default']
    DarkMode: typeof import('./components/DarkMode/index.vue')['default']
    Footer: typeof import('./components/Footer/Footer.vue')['default']
    GalleryMenu: typeof import('./components/GalleryMenu/GalleryMenu.vue')['default']
    MenuCard: typeof import('./components/MenuCard/MenuCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarMenu: typeof import('./components/SidebarMenu/SidebarMenu.vue')['default']
  }
}
